name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang
    steps:
    - uses: actions/checkout@v4.1.0
    - run: |
        whoami
        cat /etc/os-release
    - run: apt-get update && apt-get install -y python3-pip
    - run: pip install pre-commit --break-system-packages
    - run: make test
