name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-go@v5
      with:
        go-version: '1.13'
        check-latest: true
    - run: apt-get update && apt-get install -y python3-pip
    - run: pip install pre-commit --break-system-packages
    - run: make test
